# Generated by Django 5.1.1 on 2024-10-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="view_count",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
